### ISSUE TITLE
Scroll to bottom of chat messages when new message comes in

### ISSUE THREAD

**Issue by denis-kralj** [denis-kralj/reimagined-adventure#13]
Right now the history of messages stays in the same position after a new messages shows up. This is a problem when the scrollbar is present as users don't see the latest entry in the history view.

**Comment by aditya28sarin** [comment]
Can you assign me this issue?

**Comment by denis-kralj** [comment]
Preliminary solution works, I have one problem and that is scrolling to the bottom of messages when user first lands on page. The lifecycle events of the razor component don't seem to come late enough. Other then this the initial commit is kind of dirty and should be cleaned up a bit.

**Comment by denis-kralj** [comment]
Current solution feels good. Could probably be better written, but the underlying process I think works well. One improvement that I will add a ticket for is to not trigger a scroll event when the previously last message is scrolled away from.
